### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by kelvindesaeger** [Vandammecasper/Casper-Kelvin#39]
## Wat loopt er fout?

Bij het builden van de Dockerfile van de api vindt hij de files niet om de copy te doen.

![image](https://github.com/Vandammecasper/Casper-Kelvin/assets/78924360/be60261d-16d1-4d00-8680-d1abaa6fd71e)

## Waar situeert het probleem zich (beiden aanduiden kan)?

- [ ] Frontend
- [x] Backend

## Wat heb je zelf opgezocht? / Wat heeft je team-genoot geprobeerd?

Ik heb mijn code met de voorbeeldcode van de Bird repo vergeleken en ik zie geen verschillen.
Ik krijg dezelfde error ook wanneer ik de Bird repo probeer te docker builden.
Ook heb ik al de paden proberen te veranderen maar er is nog niets volledig gelukt.

## Hoe kan het probleem gereproduceerd worden op jullie repo?

docker-copose-up van de docker-compose-production.yml

## Waar staat de code die relevant is (gebruik een permalink)?

branch: feature/dockerize

https://github.com/Vandammecasper/Casper-Kelvin/tree/feature/dockerize/infrastructure
https://github.com/Vandammecasper/Casper-Kelvin/blob/feature/dockerize/packages/api/Dockerfile

**Comment by christophe-laprudence-howest** [comment]
De fout zit hier
https://github.com/Vandammecasper/Casper-Kelvin/blob/bee7fb585a70ec426a7ba7e4cb2f91e0fd94a01e/infrastructure/docker-compose-production.yml#L15-L18
De oplossing is de context juist te zetten. 
- Er moet 1 map hoger gekeken worden tov de docker-compose file. Dat is dan de `root`. 
- Tov de root kan de dockerfile gevonden worden in een child folder packages/

Als je het zo instelt, zullen de bestanden juist gekopieerd worden.
```yml
  api:
    build:
      context: ../.
      dockerfile: packages/api/Dockerfile
```
